version: "3.9"
services:
  reverse-proxy:
    image: nginx:1.15-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8080
  app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    scale: 3
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redisDb:/root/redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}

volumes:
  redisDb: