version: "3.9"
services:
  reverse-proxy:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - appNet
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - REDIS_ADDR=redis:6379
      - AUTH_CLIENT_ID=${AUTH_CLIENT_ID}
      - AUTH_CLIENT_SECRET=${AUTH_CLIENT_SECRET}
    networks:
      - appNet
    scale: 3
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redisDb:/root/redis
    environment:
      - REDIS_PASSWORD=
      - REDIS_PORT=6379
    networks:
      - appNet
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  redisDb:

networks:
  appNet:
  