definitions:
  httputil.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  models.UrlEdit:
    properties:
      originalUrl:
        type: string
      shortUrl:
        type: string
    required:
    - originalUrl
    - shortUrl
    type: object
  models.UrlInfoResponse:
    properties:
      count:
        type: integer
      ips:
        items:
          type: string
        type: array
      issuerEmail:
        type: string
      originalUrl:
        type: string
    type: object
  models.UrlShortenResponse:
    properties:
      issuerID:
        type: string
      shortUrl:
        type: string
    type: object
info:
  contact: {}
  description: This is a simple project that i am using to learn Go and other interesting
    stuff
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /{id}:
    get:
      consumes:
      - application/json
      description: Redirects to link that you have enetered on shortenURL path
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "302":
          description: Found
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Redirect to link
      tags:
      - ShortenURL
  /auth/google:
    post:
      description: Returns credentials from code sended from client
      parameters:
      - description: Code from google auth
        in: body
        name: code
        required: true
        schema:
          type: string
      responses: {}
      summary: Login
      tags:
      - Auth
  /deleteURL/{id}:
    delete:
      consumes:
      - application/json
      description: Delete link with id in case you are the owner of the link
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: id_token
        in: body
        name: id_token
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Delete link with id
      tags:
      - URL Info/Edit
  /editURL/{id}:
    patch:
      consumes:
      - application/json
      description: Edit link with id in case you are the owner of the link
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: id_token
        in: body
        name: id_token
        required: true
        schema:
          type: string
      - description: Edit Info
        in: body
        name: linkInfo
        required: true
        schema:
          $ref: '#/definitions/models.UrlEdit'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UrlEdit'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Edit link with id
      tags:
      - URL Info/Edit
  /getInfo/{id}:
    get:
      consumes:
      - application/json
      description: Get info about how many times and what IPs where entering your
        site
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UrlInfoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Info about shorten URL
      tags:
      - URL Info/Edit
  /getLinks:
    get:
      consumes:
      - application/json
      description: Get all links that associated your account if you are registered
      parameters:
      - description: id_token
        in: query
        name: id_token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Get all links
      tags:
      - ShortenURL
  /shortenURL:
    post:
      consumes:
      - application/json
      description: Shortens your  URL to small format for you to use it
      parameters:
      - description: Shorten URL
        in: query
        name: url
        required: true
        type: string
      - description: id_token
        in: body
        name: id_token
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UrlShortenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Shorten URL
      tags:
      - ShortenURL
swagger: "2.0"
