basePath: /api/v1
definitions:
  httputil.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  models.UrlShortenResponse:
    properties:
      shortURL:
        type: string
    type: object
info:
  contact: {}
  description: This is a simple project that i am using to learn Go and other interesting
    stuff
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Url-Shortener v1
paths:
  /shortenURL:
    post:
      consumes:
      - application/json
      description: shortens your  URL to small format for you to use it
      parameters:
      - description: Shorten URL
        in: query
        name: url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UrlShortenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: shorten URL
      tags:
      - shortenURL
swagger: "2.0"
